name: Publish
on:
  release:
    types:
      - published
      - edited

jobs:
  publish:
    name: Build & Publish Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build binary
        run: mvn --file pom.xml
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/SteamWarLinkManager.jar
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"